name: jenkins
services:
  controller:
    hostname: controller
    image: jenkins-controller
    build: controller
    volumes:
      - type: volume
        source: controller_home
        target: /var/jenkins_home
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: ./controller/dsl
        target: /usr/share/jenkins/dsl
        read_only: true
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins/casc/jenkins.yaml
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      JENKINS_URL_CASC: ${JENKINS_URL_CASC:-https://jenkins.mshome.net} # specify JENKINS_URL_CASC on the deployment host, or in an '.env' file which stays out of git
      TZ: Europe/CET
    env_file:
      - .env # this is not secure, but as long as the github secrets don't leak outside my lab...
    configs:
      - source: casc # convenient for development: change jenkins.yaml on-the-fly, without need to rebuild the docker image; also useful to use just the jenkins base image
        target: /var/jenkins/casc/jenkins.yaml
    secrets:
      - JENKINS_ADMINISTRATOR_USERNAME
      - JENKINS_ADMINISTRATOR_PASSWORD
      - JENKINS_SWARM_USER
      - JENKINS_SWARM_PASSWORD
      - SSH_AGENT_PRIVATE_KEY
    ports:
      - "8080:8080" # inbound agents that don't trust the myCA certificate
      - "50000:50000"
    expose:
      - "8080"
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s

  reverse-proxy:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./reverse-proxy/conf.d
        target: /etc/nginx/conf.d
        read_only: false
      - type: bind
        source: ./reverse-proxy/certs/wildcard.test.local.crt
        target: /etc/ssl/certs/wildcard.test.local.crt
        read_only: true
      - type: bind
        source: ./reverse-proxy/certs/wildcard.test.local.key
        target: /etc/ssl/private/wildcard.test.local.key
        read_only: true
      - type: bind
        source: ./reverse-proxy/certs/wildcard.mshome.net.crt
        target: /etc/ssl/certs/wildcard.mshome.net.crt
        read_only: true
      - type: bind
        source: ./reverse-proxy/certs/wildcard.mshome.net.key
        target: /etc/ssl/private/wildcard.mshome.net.key
        read_only: true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s

  test: # 'dummy' website to test the nginx configuration for multiple websites; remove the nginx config if this service should be removed
    image: nginx:stable
    deploy:
      mode: global
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s

  ssh-agent:
    image: jenkins/ssh-agent:latest-alpine-jdk21 # https://hub.docker.com/r/jenkins/ssh-agent - https://github.com/jenkinsci/docker-ssh-agent
    env_file: example-secrets/ssh-agent.env
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s

  ubuntu-swarm-agent:
    hostname: ubuntu-swarm-agent
    image: jenkins-swarm-agent
    build:
      context: swarm-agent
      dockerfile: Dockerfile
    environment:
      - JENKINS_URL=http://controller:8080
    secrets:
      - JENKINS_SWARM_USER
      - JENKINS_SWARM_PASSWORD
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
    privileged: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

  dind-agent:
    hostname: dind-agent
    image: jenkins-dind-agent
    build:
      context: dind-agent
      dockerfile: Dockerfile
    environment:
      - JENKINS_URL=http://controller:8080
      - DOCKER_TLS_CERTDIR=/certs
    secrets:
      - JENKINS_SWARM_USER
      - JENKINS_SWARM_PASSWORD
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s

volumes:
  controller_home:

configs:
  casc:
    file: controller/jenkins.yaml

secrets:
  JENKINS_ADMINISTRATOR_USERNAME:
    file: ./example-secrets/admin-user
  JENKINS_ADMINISTRATOR_PASSWORD:
    file: ./example-secrets/admin-password
  JENKINS_SWARM_USER:
    file: ./example-secrets/swarm-user
  JENKINS_SWARM_PASSWORD:
    file: ./example-secrets/swarm-password
  SSH_AGENT_PRIVATE_KEY:
    file: ./example-secrets/ssh_agent_id_rsa
